### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Milky063** [AlexHaible/BetterBags-Appearances#1]
6x BetterBags/frames/bag.lua:147: attempt to index field 'currentView' (a nil value)
[string "@BetterBags/frames/bag.lua"]:147: in function `Sort'
[string "@BetterBags/frames/bag.lua"]:469: in function <BetterBags/frames/bag.lua:450>

Locals:
self = <table> {
 menuList = <table> {
 }
 searchBox = <table> {
 }
 sections = <table> {
 }
 toRelease = <table> {
 }
 slots = <table> {
 }
 toReleaseSections = <table> {
 }
 currencyFrame = <table> {
 }
 moneyFrame = <table> {
 }
 isReagentBank = false
 drawOnClose = false
 views = <table> {
 }
 currentItemCount = 0
 kind = 0
 bottomBar = Frame {
 }
 frame = BetterBagsBagBackpack {
 }
 drawAfterCombat = false
 resizeHandle = Button {
 }
}
lockList = <table> {
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'currentView' (a nil value)"
const = <table> {
 BANK_ONLY_BAGS = <table> {
 }
 BAG_KIND = <table> {
 }
 Enable = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 BANK_BAGS = <table> {
 }
 BANK_ONLY_BAGS_LIST = <table> {
 }
 BRIEF_EXPANSION_MAP = <table> {
 }
 DATABASE_DEFAULTS = <table> {
 }
 SECTION_SORT_TYPE = <table> {
 }
 SetDefaultModulePrototype = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 name = "BetterBags_Constants"
 IsEnabled = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 DisableModule = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:346
 OFFSETS = <table> {
 }
 ITEM_QUALITY_COLOR = <table> {
 }
 baseName = "BetterBags"
 TRADESKILL_MAP = <table> {
 }
 EXPANSION_MAP = <table> {
 }
 ITEM_SORT_TYPE = <table> {
 }
 GetName = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 IsModule = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:213
 ITEM_QUALITY_HIGHLIGHT = <table> {
 }
 SetDefaultModuleState = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:383
 EXPANSION_TYPE = <table> {
 }
 ITEM_QUALITY_COLOR_LOW = <table> {
 }
 SetEnabledState = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 SetDefaultModuleLibraries = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 enabledState = false
 BACKPACK_ONLY_REAGENT_BAGS = <table> {
 }
 BAG_VIEW = <table> {
 }
 GRID_COMPACT_STYLE = <table> {
 }
 BACKPACK_ONLY_BAGS_LIST = <table> {
 }
 Disable = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 defaultModuleLibraries = <table> {
 }
 IterateModules = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:433
 BACKPACK_BAGS = <table> {
 }
 REAGENTBANK_BAGS = <table> {
 }
 ITEM_QUALITY_COLOR_HIGH = <table> {
 }
 moduleName = "Constants"
 defaultModuleState = true
 BACKPACK_ONLY_BAGS = <table> {
 }
}
items = <table> {
 RefreshBank = <function> defined @BetterBags/data/items.lua:190
 SetDefaultModuleLibraries = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 RefreshBag = <function> defined @BetterBags/data/items.lua:375
 OnInitialize = <function> defined @BetterBags/data/items.lua:58
 RemoveNewItemFromAllItems = <function> defined @BetterBags/data/items.lua:122
 EnableModule = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 defaultModu

**Comment by AlexHaible** [comment]
This isn't due to my plugin, I'm afraid. The stack trace there indicates it's a bug within BetterBags itself.
