### ISSUE TITLE
RFE: Option to separate by slot

### ISSUE THREAD

**Issue by SpareSimian** [AlexHaible/BetterBags-Appearances#6]
Item icons can sometimes be hard to distinguish for those of us with old eyes, so splitting the tradable items by slot would make it easier to allocate items to alts who need a particular slot upgraded.

**Comment by AlexHaible** [comment]
There's already an checkbox to split tradable by armor type in the options. That should do the trick, should it not?

**Comment by SpareSimian** [comment]
That seems to split based on plate/mail/leather/cloth, which is definitely useful. I'm looking for character slot splitting, like head/chest/boots/etc.

**Comment by SpareSimian** [comment]
Thanks! Works great!
